### ISSUE TITLE
为何无法下载？

### ISSUE THREAD

**Issue by bluefo** [NoManTeam/Hole#2]
rt

**Comment by ghost** [comment]
您好，感谢关注。
因为此项目已终止多年。
不过我们注意到，这些年来，也出现了个别替代品，尽管......此时那些「借鉴者」的iOS版应用多半也难以下载......至少他们人比较多，而我们已经无以为继了。
希望这多少可以帮到您。

**Comment by bluefo** [comment]
非常感谢回复。
我近几年一直在想，手机上得有这么个东西，两边都持有密钥，且是依附在输入法上实现的的加解密工具，才能是真正意义上的隐私通信。可惜我前几天才发现这个项目，虽然不能用了，不过，地球上还是有和自己想到一起的人，真是很欣慰。
祝你们好。
